"""create Date and CycleEvent tables

Revision ID: 149fcd777b9e
Revises: 
Create Date: 2021-06-12 17:37:15.267852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '149fcd777b9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycleevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycleevent_type_'), 'cycleevent', ['type_'], unique=True)
    op.create_table('date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_date_date_'), 'date', ['date_'], unique=True)
    op.create_table('date_cycle_event',
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('cycleevent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cycleevent_id'], ['cycleevent.id'], ),
    sa.ForeignKeyConstraint(['date_id'], ['date.id'], ),
    sa.PrimaryKeyConstraint('date_id', 'cycleevent_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('date_cycle_event')
    op.drop_index(op.f('ix_date_date_'), table_name='date')
    op.drop_table('date')
    op.drop_index(op.f('ix_cycleevent_type_'), table_name='cycleevent')
    op.drop_table('cycleevent')
    # ### end Alembic commands ###
